### ISSUE TITLE
what is this static String supabseSecret = "xxxxxxxxxxxxx";? i have to change this?

### ISSUE THREAD

**Issue by PrijensNakrani** [Calentre/calentre#6]
static String supabseSecret = "xxxxxxxxxxxxx";

it is present in secrets,example.dart screen

**Comment by fiizzy** [comment]
Hi, @PrijensNakrani you have to create a Supabase account, create a new project, and then fetch the API key and use it within the Calentre project.
I am currently working on a more comprehensive contributing guide. I'll share that with you once available.
In the meantime, you can join our [discord channel](https://discord.gg/KU69EeWe) for more direct help.
